### ISSUE TITLE
Slic3r compatibility

### ISSUE THREAD

**Issue by Maelep** [ChristophSchranz/Octoprint-PrePrintService#1]
Is your plugin compatible with PrusaSlicer 2.0 profile?

**Comment by ChristophSchranz** [comment]
I don't know, let's try it please and let us know!

**Comment by Maelep** [comment]
I would like to try but I have sooo many problems to use your plugins :/

You said that Docker is optional then you said that it is highly
recommended... I tried without docker, not working.I tried to install
docker, not working...

Your You setup explanation isn't working :/ Can you update it?

**Comment by ChristophSchranz** [comment]
I recommend the usage of Docker to get independent of different setups, but if you haven't installed Docker yet, it's easier to try it without it. (on Win!=10 it isn't nice to install)
Can you run `preprintservice_src/tweak-service.py` such that the service is accessible on port `2304`?
There you can already test your SlicingProfile.

**Comment by Maelep** [comment]
I'm actually trying to install PrePrintService on my Raspberry 3B+ that run
OctoPi.
I know that this Raspberry isn't powerful to run your plugin well but I
just want to try if I can't run it before installing it on a more powerful
server.

So, I followed your setup instruction but it isn't working, I can't access
to <OctoPiIP>:2304/tweak <http://localhost:2304/tweak>
I tried to install Docker and Docker-compose, got many problems.

If I understand correctly, I just have to import my settings then upload a
.STL and click the slice button?

**Comment by ChristophSchranz** [comment]
> I'm actually trying to install PrePrintService on my Raspberry 3B+ that run
OctoPi.
I know that this Raspberry isn't powerful to run your plugin well but I
just want to try if I can't run it before installing it on a more powerful
server.

@Maelep Installing that on a RPi is an extrem overload. I've also the Octoprint server on a RPi for which is suffices, but the PrePrintServer does Slicing and Auto-rotating which demands very very much vector operations that can't be done efficiently on a RPi's ARM/RISC processor. I've tried both components, but never the PrePrintServer, as it lasts for several minutes instead of 1-2 seconds.
I would suggest you try the setup on a server node or locally, that would be much faster.

> So, I followed your setup instruction but it isn't working, I can't access
to <OctoPiIP>:2304/tweak <http://localhost:2304/tweak>
I tried to install Docker and Docker-compose, got many problems.

What does the log say? Do you see that [Interface](https://github.com/ChristophSchranz/Octoprint-PrePrintService/blob/master/extras/PrePrintService.png)

**Comment by Maelep** [comment]
Yes, I now that a Raspberry Pi isn't powerful enough to run your plugin but
to overload my RPi, it has to work first xD
If I can run your plugins, I will buy a more powerful server to run it :)

I don't get any interfaces :/
The only thing I got is a "link" on the top of Octoprint "Using PrePrint
Service <http://192.168.48.81:2304/tweak>" but it's not working, it's
unavailable.
This site can’t be reached

*192.168.48.81* took too long to respond.



Is your plugin works if I install a fresh OctoPi, install the plugin with
the plugin manager?
Could you explain how to use the plugin from the start?
I think many peoples give up because there isn't any tutorial :/

**Comment by ChristophSchranz** [comment]
> The only thing I got is a "link" on the top of Octoprint "Using PrePrint
Service <http://192.168.48.81:2304/tweak>" but it's not working, it's
unavailable.

The IP `192.168.48.81` is an example. Use the ip of your Pi `<your_ip>:2304/tweak`, or if run on the same node `localhost:2304/tweak`

You also get a lot of information in the console output of your the service (`preprintservice_src/tweak-service.py`)

**Comment by Maelep** [comment]
I installed a fresh copy of OctoPi,
I installed your plugin using the plugin manager,
I tried to open http://192.168.0.24:2304/tweak (it's the IP of my OctoPi)
It's not working.

[image: image.png]
[image: image.png]

**Comment by ChristophSchranz** [comment]
I'm sorry, I can't see the images and you should really provide and read the terminal output.

**Comment by Maelep** [comment]
I don't have terminal output because I'm connected to my RPi by SSH :/
The first image show the settings of your plugins and the second image is
what I get when I try to connect to your plugins:
This site can’t be reached
192.168.0.24 refused to connect.
Search Google for 192 168 2304 tweak
ERR_CONNECTION_REFUSED

**Comment by ChristophSchranz** [comment]
> I don't have terminal output because I'm connected to my RPi by SSH :/
I don't know how you want to execute the code then and I can't read tea leaves.

Why don't you connect via ssh, clone this repository and run the python server to actually start the server?

**Comment by ChristophSchranz** [comment]
Closing this issue as there seems to be no reason, that the plugin or server has a problem.
