### ISSUE TITLE
File not found and no auto rotate file generated

### ISSUE THREAD

**Issue by davidfeeney** [ChristophSchranz/Octoprint-PrePrintService#2]
I have run into two issues with the plugin. First I randomly get the error FileNotFoundError when using the testing UI on the host node. Checking out the logs I see something like this:

```
pre-print-service_1  | [2020-01-19 16:59:58,975] INFO in tweak-service: Running Tweak with command: 'python3 /src/Tweaker-3/Tweaker.py -i /src/uploads/13012020_34961_Body.stl -x -vol -t binarystl -o /src/uploads/tweaked_13012020_34961_Body.stl'
pre-print-service_1  | Traceback (most recent call last):
pre-print-service_1  |   File "/src/Tweaker-3/FileHandler.py", line 26, in load_mesh
pre-print-service_1  |     objs = self.load_ascii_stl(f)
pre-print-service_1  |   File "/src/Tweaker-3/FileHandler.py", line 72, in load_ascii_stl
pre-print-service_1  |     for line in f:
pre-print-service_1  |   File "/usr/local/lib/python3.6/codecs.py", line 321, in decode
pre-print-service_1  |     (result, consumed) = self._buffer_decode(data, self.errors, final)
pre-print-service_1  | UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8e in position 80: invalid start byte
```

Second, when using the Octoprint UI and the auto-rotate only option, it doesn't seem to do anything when dragging in an STL file. The response in the logs says:

>  INFO in tweak-service: Sending back file was skipped as expected

Why is sending the file back being skipped? I would expect to see a new file added to the Octoprint queue with the tweaked version.

**Comment by ChristophSchranz** [comment]
Hi @davidfeeney,
I'm afraid I don't find time at the moment to correct this bug and make it more robust, I hope it will work in February.
It seems that your object file is actually a binary STL file with a inconvenient header. This bad format makes the module think that it is an ASCII encoded STL file even though it is not. Does it work with other files?

Has the second error occurred, if the object from bug 1 was used? 
Then there was an internal error and the message is misleading!

**Comment by ChristophSchranz** [comment]
I've checked now the Traceback and the code and it wonders me quite a lot that an error is thrown although it should be caught. I'm not sure if you use an ASCII or binary encoded STL format and if it is correct. Have you had problems in opening this file with other software? I guess your file is a little bit different and I run into a problem within the exception block.. If you attach it here (or send it via mail to me) I'll try to figure out the problem! That could help others with similar issues too!

**Comment by ChristophSchranz** [comment]
Okay, I now also understand your first issue too. If you could send me your object (in a personal message) I'll fix that issue!

**Comment by davidfeeney** [comment]
Hi @ChristophSchranz I have worked with the binary encoded STL format for many years as exported from various CAD programs and have never had a problem reading the output STL file in any other software program. I've attached two variants of the same object here, one is ASCII encoded, the other is binary. The ASCII encoded version seems to work fine and the binary version does not. Let me know if you are able to get this working!
[button.zip](https://github.com/ChristophSchranz/Octoprint-PrePrintService/files/4118320/button.zip)

**Comment by davidfeeney** [comment]
Also, for issue 2 I get the following response in the pre-print-service logs:

`pre-print-service_1  | 172.18.0.1 - - [27/Jan/2020 17:11:51] "GET / HTTP/1.1" 200 -`
`pre-print-service_1  | 172.18.0.1 - - [27/Jan/2020 17:11:52] "GET / HTTP/1.1" 200 -`

and in the plugin logs I have:
`2020-01-27 09:17:44,965 - octoprint.plugins.preprintservice - INFO - Connection to PrePrintService on ... is ready, status code 200`
`2020-01-27 09:17:45,101 - octoprint.plugins.preprintservice - INFO - Connection to Octoprint server on ... is ready, status code 200`

So it seems like the server is accessible and the plugin is accessible but nothing else happens once you drag in an STL file. Same behavior for either ASCII or binary formats.

**Comment by ChristophSchranz** [comment]
I've tried to fix this bug:
- The Tweaker-3 where this bug origins from has now an improved traceback for this kind of issue. (Without your corrupted model I can't fix it)
- The flash notifs from octoprint are hard to access, at least I couldn't when I made this plugin. Therefore, if there goes something wrong in the preprocessing, it is not straight to forward this info to Octoprint.

**Comment by davidfeeney** [comment]
Were you able to test the two files I sent you? One is the binary which doesn't work and the other is ASCII which does work. Attaching them here in a zip file: 
[button.zip](https://github.com/ChristophSchranz/Octoprint-PrePrintService/files/4142786/button.zip)

**Comment by ChristophSchranz** [comment]
Thank you for the file!
I've found the bug in Tweaker-3 which is solved with this [commit](https://github.com/ChristophSchranz/Tweaker-3/commit/5bfaf5f72b211e378b1eb73f04c185e90397090a)

Now it should work, as soon as you repull the Tweaker (Auto-Orientation) Module. This is done easily using:

```bash
# stop and rm running instance
docker ps | grep "pre-print-service" | awk '{print $1}' | xargs docker rm -f 

# remove docker image of pre-print-service (make sure custom profiles are saved)
docker image ls | grep "pre-print-service" | awk '{print $3}'  | xargs docker image rm

# reload and restart the service
cd OctoPrint-PrePrintService
docker-compose up --build -d
```

Alternatively, you can also insert a `RUN apt-get update` right before the clone of the `Tweaker-3` in the `Dockerfile`.
