### ISSUE TITLE
PrusaSlicer Support

### ISSUE THREAD

**Issue by lehighkid** [ChristophSchranz/Octoprint-PrePrintService#3]
First thank you for this - I am excited to not have to switch between my iPad and computer just to slice.

I was hoping to use this w/ the latest version of PrusaSlicer by changing
`SLIC3R_VERSION=https://github.com/prusa3d/Slic3r/releases/download/version_1.41.3/Slic3rPE-1.41.3+linux64-full-201902121303.tar.bz2`
to 
`SLIC3R_VERSION=https://github.com/prusa3d/PrusaSlicer/releases/download/version_2.2.0/PrusaSlicer-2.2.0+linux-x64-202003211856.tar.bz2`

but it didn't work - it ended up resulting in an error:
`pre-print-service_1  | Segmentation fault
pre-print-service_1  | [2020-05-01 22:17:10,819] ERROR in tweak-service: Slicing was executed with the warning: .
pre-print-service_1  | [2020-05-01 22:17:10,820] INFO in tweak-service: Sending file '/src/uploads/TEST.gco' to URL 'https://octoprint.mydomain.com/api/files/local'
pre-print-service_1  | XXX.XX.0.1 - - [01/May/2020 22:17:10] "POST /tweak HTTP/1.1" 500 -`

any thoughts on where else I would have to make changes - I tried to edit the following in tweak-service.py:
`app.config['SLIC3R_PATHS'] = ["/Slic3r/slic3r-dist/slic3r", "/home/chris/Documents/software/Slic3r/Slic3rPE-1.41.2+linux64-full-201811221508/slic3r"]`

as neither of these paths were there but it didn't appear to make a difference.

Thx!

**Comment by ChristophSchranz** [comment]
Hi @lehighkid 
unfortunately, I don't ad hoc an answer to this issue.
Does it work stand-alone, by just running the service in python?
If so, you  could examine the paths inside the docker container using `docker exec -it [UID] bash`.

Please let me know how you fixed it! :)

**Comment by lehighkid** [comment]
Thank you for the response.  I will try w/ Python.  I did check the paths in Docker and they do appear different but wasn’t sure where else to update.  I’ll keep tinkering but it does work w/ my 2.20 configs using your docker-compose.yml for now.

**Comment by ChristophSchranz** [comment]
Sorry for being so late. Now the Slic3r was updated to version 2.2.0 with commit 1f803becc3a867b7405a1d2caf602dfb35a8a8fb. The issue was a changed API as documented [here](https://manual.slic3r.org/advanced/command-line).
Let me know if there is still an error!
