### ISSUE TITLE
FEATURE REQUEST:  Add Option to Disable Navbar Link

### ISSUE THREAD

**Issue by lehighkid** [ChristophSchranz/Octoprint-PrePrintService#4]
Is it possible to add an option to remove the help link in the navbar "Using PrePrint Service"?  Once it is set up and testing, I'm not really sure of the value of having it take up critical real estate.

**Comment by ChristophSchranz** [comment]
I've removed this info completely in a262e592eed31b515368bb9b380f111c57c456d9.

Thanks, for the request!

**Comment by lehighkid** [comment]
Thank you!  I tried updating and then pulling this specific commit and uploading the plugin manually but it didn't change.  Any suggestions?

**Comment by ChristophSchranz** [comment]
Maybe the pip install didn't delete the file `octoprint_preprintservice/templates/preprintservice_navbar.jinja2` automatically.
Can you re-install the plugin via pip and then check if this file exists in the libraries of the octoprint environment?
