### ISSUE TITLE
request for upgrade to py3

### ISSUE THREAD

**Issue by Mafaldone** [ChristophSchranz/Octoprint-PrePrintService#6]
Hi man, are you planning to move upgrade to python 3.8?

**Comment by ChristophSchranz** [comment]
Not at the moment.
I found a guide to [upgrade a repo to Python 3](https://octoprint.org/blog/2020/09/10/upgrade-to-py3/).  Maybe this helps you!

**Comment by cp2004** [comment]
There are changes that need to be made in the plugin, to make it Python 3 compatible. The guide you linked is for upgrading an install to Py3, but this plugin is not compatible so it will not work with that guide.
Here are some docs on how to update the plugin: https://docs.octoprint.org/en/master/plugins/python3_migration.html#migrating-to-python-3

At some point, OctoPrint will drop support for Python 2, and your plugin will no longer work. (Not before March 2021, but we are trying to get this moving as fast as possible).

**Comment by ChristophSchranz** [comment]
Okay the Plugin is updated to Python 3 and windows is now also supported (okay, I've parametrized the executing python path such that it works for Windows too).
Let me know if it works for you :)
