### ISSUE TITLE
Thumbnails

### ISSUE THREAD

**Issue by padic-dev** [ChristophSchranz/Octoprint-PrePrintService#7]
Is there a way to embed thumbnails into the sliced gcode file? This works fine in the windows desktop version but I cannot seem to find any information on handling thumbnails using the command line slicer.

I have the thumbnail property set to 16x16,235x235 in my profile ini file just as is used in the windows desktop version. I also tried adding --thumbnails 16x16,235x235 but the base64 thumbnail code is not injected into the sliced gcode.

**Comment by ChristophSchranz** [comment]
It is not supported and not planned to be. However, you can make a PR for that!
