### ISSUE TITLE
tweak http error code 500

### ISSUE THREAD

**Issue by hackex** [ChristophSchranz/Octoprint-PrePrintService#8]
Hi there,
I was trying to use the PrePrintService in my Octoprint installation. I am using everything on the same machine (a good linux server).
I can reach the tweak webpage and create gcode files. But on usage on octoprint, trying to slice a .stl-file I get an 500 error:

`2021-01-06 20:24:11,661 - octoprint.filemanager.analysis - INFO - Analysis of entry local:z3.gco finished, needed 0.85s
2021-01-06 20:24:13,564 - octoprint.plugins.preprintservice - INFO - POST to service with status code: 500
2021-01-06 20:24:13,564 - octoprint.plugins.preprintservice - ERROR - Got http error code 500 on request http://ip-address:2304/tweak
2021-01-06 20:24:13,564 - octoprint.plugins.preprintservice - INFO - Couldn't post to http://ip-address:2304/tweak`

What am I doing wrong. Only a non-usable 76bytes gco-file is being created in octoprint. I was wondering anywhere how to get a profile configuration file to be used with the service. I ended up installing slic3r on my linux machine, put all the printer settings (bed size, filament size..) in there and export the settings to an .ini-file. That file I then used as a profile in the plugin-page of the preprint-service in octopring.

Could anyone give me a hint of what I am doing wrong? I would appreciate it.

**Comment by ChristophSchranz** [comment]
What are the results if you follow the [Testing procedure](https://github.com/ChristophSchranz/Octoprint-PrePrintService#testing) for debugging?

**Comment by hackex** [comment]
> What are the results if you follow the [Testing procedure](https://github.com/ChristophSchranz/Octoprint-PrePrintService#testing) for debugging?

Hi,
Everything works fine in the testing procedure. My error code seems to be similar like the last code paragraph you show in the procedure, e.g. cannot post on IP...error 500 (you mention some profile problem in your instructions).

**Comment by ChristophSchranz** [comment]
Is the IP of octoprint reachable on the node that runs the Preprocessing/Tweaker?
If yes, this is the IP address you should use in the Settings of this Plugin.

**Comment by hackex** [comment]
> Is the IP of octoprint reachable on the node that runs the Preprocessing/Tweaker?
> If yes, this is the IP address you should use in the Settings of this Plugin.

Hi,
Yes, I can reach the tweak IP address and also sliced STL-file there to get a gcode file. Actually, sometimes I get only a .bin-file trying to tweak and slice (only tweak gives me a rotated STL).
Any ideas?
Thank you

**Comment by ChristophSchranz** [comment]
It is the expected behaviour, "tweaking" means auto-rotation.

The `.bin`-file seems strange. Do you have some logging output of the preprocess-server (not the Octoprint-server)?

**Comment by hackex** [comment]
> It is the expected behaviour, "tweaking" means auto-rotation.
> 
> The `.bin`-file seems strange. Do you have some logging output of the preprocess-server (not the Octoprint-server)?

Hi,
the log for the preprint-server are as follows using the `docker-compose logs -f` command:

`[2021-02-01 20:27:46,790] DEBUG in tweak-service: Handling the download of '/src/uploads/MicroSD_Card_Holder.gcode'.
pre-print-service_1  | 172.23.0.1 - - [01/Feb/2021 20:27:46] "POST /tweak HTTP/1.1" 200 -
pre-print-service_1  | localip - - [01/Feb/2021 20:29:27] "GET /tweak HTTP/1.1" 200 -
pre-print-service_1  | localip - - [01/Feb/2021 20:29:41] "GET /tweak HTTP/1.1" 200 -
pre-print-service_1  | localip - - [01/Feb/2021 20:29:41] "GET /tweak HTTP/1.1" 200 -
pre-print-service_1  | localip - - [01/Feb/2021 20:29:41] "GET /tweak HTTP/1.1" 200 -
pre-print-service_1  | localip - - [01/Feb/2021 20:29:41] "GET /tweak HTTP/1.1" 200 -
pre-print-service_1  | localip - - [01/Feb/2021 20:29:41] "GET /tweak HTTP/1.1" 200 -
pre-print-service_1  | localip - - [01/Feb/2021 20:29:41] "GET /tweak HTTP/1.1" 200 -
pre-print-service_1  | localip - - [01/Feb/2021 20:29:41] "GET /tweak HTTP/1.1" 200 -
pre-print-service_1  | localip - - [01/Feb/2021 20:29:41] "GET /tweak HTTP/1.1" 200 -
pre-print-service_1  | [2021-02-01 20:29:41,307] DEBUG in tweak-service: request on: <Request 'http://localip:2304/tweak' [POST]>
pre-print-service_1  | [2021-02-01 20:29:41,314] INFO in tweak-service: Getting request from octoprint server: http://localip:5000/api/files/local
pre-print-service_1  | [2021-02-01 20:29:41,314] INFO in tweak-service: Uploaded new model: MicroSD_Card_Holder.stl
pre-print-service_1  | [2021-02-01 20:29:41,315] INFO in tweak-service: Saved model to /src/uploads/MicroSD_Card_Holder.stl
pre-print-service_1  | [2021-02-01 20:29:41,316] INFO in tweak-service: Uploaded new profile: slicing-profile-temp-u8if1em9.profile
pre-print-service_1  | [2021-02-01 20:29:41,316] INFO in tweak-service: Using profile: /src/profiles/slicing-profile-temp-u8if1em9.profile
pre-print-service_1  | [2021-02-01 20:29:41,316] INFO in tweak-service: Using Tweaker actions: tweak, slice, get_tweaked_stl
pre-print-service_1  | [2021-02-01 20:29:41,316] INFO in tweak-service: Machinecode will have name a.gco
pre-print-service_1  | [2021-02-01 20:29:41,317] INFO in tweak-service: Running Tweak with command: '/usr/local/bin/python3 /src/Tweaker-3/Tweaker.py -i /src/uploads/MicroSD_Card_Holder.stl -x -t binarystl -o /src/uploads/tweaked_MicroSD_Card_Holder.stl'
pre-print-service_1  | [2021-02-01 20:29:42,023] INFO in tweak-service: Tweaking was successful
pre-print-service_1  | [2021-02-01 20:29:42,025] INFO in tweak-service: Sending file '/src/uploads/tweaked_MicroSD_Card_Holder.stl' to URL 'http://localip:5000/api/files/local'
pre-print-service_1  | 192.168.178.67 - - [01/Feb/2021 20:29:43] "POST /tweak HTTP/1.1" 500 -
pre-print-service_1  | Traceback (most recent call last):
pre-print-service_1  |   File "/usr/local/lib/python3.6/site-packages/urllib3/connection.py", line 159, in _new_conn
pre-print-service_1  |     (self._dns_host, self.port), self.timeout, **extra_kw)
pre-print-service_1  |   File "/usr/local/lib/python3.6/site-packages/urllib3/util/connection.py", line 80, in create_connection
pre-print-service_1  |     raise err
pre-print-service_1  |   File "/usr/local/lib/python3.6/site-packages/urllib3/util/connection.py", line 70, in create_connection
pre-print-service_1  |     sock.connect(sa)
pre-print-service_1  | ConnectionRefusedError: [Errno 111] Connection refused
pre-print-service_1  | 
pre-print-service_1  | During handling of the above exception, another exception occurred:
pre-print-service_1  | 
pre-print-service_1  | Traceback (most recent call last):
pre-print-service_1  |   File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
pre-print-service_1  |     chunked=chunked)
pre-print-service_1  |   File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 354, in _make_request
pre-print-service_1  |     conn.request(method, url, **httplib_request_kw)
pre-print-service_1  |   File "/usr/local/lib/python3.6/http/client.py", line 1287, in request
pre-print-service_1  |     self._send_request(method, url, body, headers, encode_chunked)
pre-print-service_1  |   File "/usr/local/lib/python3.6/http/client.py", line 1333, in _send_request
pre-print-service_1  |     self.endheaders(body, encode_chunked=encode_chunked)
pre-print-service_1  |   File "/usr/local/lib/python3.6/http/client.py", line 1282, in endheaders
pre-print-service_1  |     self._send_output(message_body, encode_chunked=encode_chunked)
pre-print-service_1  |   File "/usr/local/lib/python3.6/http/client.py", line 1042, in _send_output
pre-print-service_1  |     self.send(msg)
pre-print-service_1  |   File "/usr/local/lib/python3.6/http/client.py", line 980, in send
pre-print-service_1  |     self.connect()
pre-print-service_1  |   File "/usr/local/lib/python3.6/site-packages/urllib3/connection.py", line 181, in connect
pre-print-service_1  |     conn = self._new_conn()
pre-print-service_1  |   File "/usr/local/lib/python3.6/site-packages/urllib3/connection.py", line 168, in _new_conn
pre-print-service_1  |     self, "Failed to establish a new connection: %s" % e)
pre-print-service_1  | urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7fb7185c32e8>: Failed to establish a new connection: [Errno 111] Connection refused
pre-print-service_1  | 
pre-print-service_1  | During handling of the above exception, another exception occurred:
pre-print-service_1  | 
pre-print-service_1  | Traceback (most recent call last):
pre-print-service_1  |   File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
pre-print-service_1  |     timeout=timeout
pre-print-service_1  |   File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
pre-print-service_1  |     _stacktrace=sys.exc_info()[2])
pre-print-service_1  |   File "/usr/local/lib/python3.6/site-packages/urllib3/util/retry.py", line 399, in increment
pre-print-service_1  |     raise MaxRetryError(_pool, url, error or ResponseError(cause))
pre-print-service_1  | urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localip', port=5000): Max retries exceeded with url: /api/files/local?apikey=secret (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb7185c32e8>: Failed to establish a new connection: [Errno 111] Connection refused',))`

Sorry for the bad code format. I replaced my ip address with "localip". Any ideas? At least I get .gcode files using the webpage for tweaking. But somehow the gcode doesn't end up in my printer's sdcard when slicing with preprint-service over the octoprint printer page.

**Comment by ChristophSchranz** [comment]
You can't connect to the service. Try to use the ip address of the device.

**Comment by hackex** [comment]
> You can't connect to the service. Try to use the ip address of the device.

Hi,
I am using my local ip address to connect. Also in octorprint preprint service setting I use 192.168.xxx.xx:5000.

**Comment by ChristophSchranz** [comment]
Can you run the preprint server without Python? Maybe there is a Docker issue that prevents it from accessing the host's IP.

**Comment by hackex** [comment]
> Can you run the preprint server without Python? Maybe there is a Docker issue that prevents it from accessing the host's IP.

You mean run it without docker and directly on python?
How do I do that? Is there a pip package?

Or how do I run it without python?

**Comment by ChristophSchranz** [comment]
Just run https://github.com/ChristophSchranz/Octoprint-PrePrintService/blob/master/preprintservice_src/tweak-service.py
